
export const posts = [{
    "slug": "what-is-bio-food",
    "title": "What is Bio Food",
    "author": "Max Ka",
    "authorRole": "Graphic Designer, educator & CEO BioFood",
    "date": "August 20, 2023",
    "description": "The trend of bio food, also known as organic food, is gaining popularity among consumers. Learn more about the benefits of bio foods and why they are attracting many customers.",
    "body": "BIO is a noticeable trend which is attracting many customers. Every day more products have the BIO symbol. What is the differences between organic and non-organic food? <br> Organic food has simply more of the antioxidant and lower levels of toxic metals and pesticides. Moreover, no fertilizers of mineral origin, hormones, genetically modified organisms and other substances which damage environment can be used during the product growing. <br><br><b><h2>How to recognize bio food?</h2></b> <br>For agricultural products, BIO means that the item was grown following the rules of the EU Regulation on Organic Farming. For processed foods, the label BIO means that at least 95% of the ingredients of agricultural origin come from organic farming. It is forbidden to use this label for genetically modified food products. The regulations also forbid to use the label for products with many E or stabilizers. <br><br> BIO foods is simply recognized for their indication with European BIO logo. EU Organic Logo has two roots – two well known symbols. The first is European flag – official symbol of the EU. The second is a leaf that is used in a variety of shapes to symbolise nature and sustainability. The combination of these two symbols creates a unique visual EU organic logo. One of Polish company – OSM Piątnica decided a few months ago to introduce to the market new line of BIO veggies and BIO products. <br><br> <b><h2>You will find in OSM Piątnica offer:</h2></b> <br> • <b>Bio cottage cheese</b> – cottage cheese made from organic milk. It is natural, does not contain any preservatives or other additives and is made of delicate grains of cottage cheese dipped in sweet cream. <br> • <b>Bio cream 18%</b> – this thick sour cream with 18% fat is produced exclusively from organic pasteurized cream and live cultures of bacteria. Perfect for enriching the taste of traditional Polish soups, sauces and salads. <br> • <b>Bio curd cottage cheese</b> – this semi-skimmed cottage cheese is completely natural, as it contains only pasteurized milk and live cultures of bacteria. It is made from milk from certified organic farms. <br> • <b>Bio organic milk</b> – comes from certified organic farms that operate traditional pasture-based cow dairies. The cows are fed with natural fodders that are produced mainly on the same farm. They are grazed on pastures where neither artificial fertilizers nor synthetic plant protection products are used. All OSM Piątnica BIO products can be found in stores, where BIOfood delivers its products",
    "image": "/blog-1.jpg",
    "keywords": "Bio food"
  },
  {
    "slug": "bio-organic-products-at-our-farms",
    "title": "Bio organic products at our farms",
    "author": "Max Ka",
    "authorRole": "Graphic Designer, educator & CEO BioFood",
    "date": "July 05, 2023",
    "description": "Discover 100% Bio Organic Food at our farms. No cross-contamination, no synthetic pesticides. Shop our wide selection of affordable produce today.",
    "body": "Every basket of strawberries, every bushel of apples, and every beet bunch in our produce department is 100% organic. We are 100% bio food company. <br><br><br> <b><h2>Organic farming</h2></b> <br> Organic farming, also known as ecological farming or biological farming, is an agricultural system that uses fertilizers of organic origin such as compost manure, green manure, and bone meal and places emphasis on techniques such as crop rotation and companion planting. It originated early in the 20th century in reaction to rapidly changing farming practices. Certified organic agriculture accounts for 70 million hectares (170 million acres) globally, with over half of that total in Australia. Organic farming continues to be developed by various organizations today. Biological pest control, mixed cropping, and the fostering of insect predators are encouraged. Organic standards are designed to allow the use of naturally-occurring substances while prohibiting or strictly limiting synthetic substances. For instance, naturally-occurring pesticides such as pyrethrin are permitted, while synthetic fertilizers and pesticides are generally prohibited. Synthetic substances that are allowed include, for example, copper sulfate, elemental sulfur, and ivermectin. Genetically modified organisms, nanomaterials, human sewage sludge, plant growth regulators, hormones, and antibiotic use in livestock husbandry are prohibited. Our bio food company follows these trends, so we could deliver better bio food products to our customers. Organic farming advocates claim advantages in sustainability,openness, self-sufficiency, autonomy and independence,health, food security, and food safety. <br><br><br> <b><h2>BIOfood farms</h2></b> <br> And yes, that's right, we only sell 100% bio food products, not 95%, not 75%, not 5%. Really and truly 100% bio food. Unlike the other guys, (who proclaim in giant letters that they carry bio products food and make you trek all the way to the back just to find the teeny, tiny organic produce section) you don't have to worry about the risk of cross-contamination from synthetic pesticides, or waste time trying to figure out which apple varieties are organic. We strongly believe that bio organic products can improve our health and lives. We're the only large grocery store chain to offer 100% organic produce, so isn't it about thyme to shop with us? Check out our wide selection of bio healthy food, always affordable produce today.<br><br> You can find out where our farms are located or how to order in Services.",
    "image": "/blog-2.jpg",
    "keywords": "Bio organic products, Bio food products, Bio food company"
  },
  {
    "slug": "bio-organic-products-online-for-those-who-pay-attention-to-health",
    "title": "Bio-Organic Products online for those who pay attention to health!",
    "author": "Max Ka",
    "authorRole": "Graphic Designer, educator & CEO BioFood",
    "date": "June 12, 2023",
    "description": "Discover Bio-Organic Products Online for Health-Conscious Consumers. Shop Now for Chemical-Free Farming Products. Visit Our Farms or Order for Delivery.",
    "body": "Bio-Organic is a current of agriculture that has been spreading more and more in the world over the last few years, especially in health-conscious consumers who are interested in how products are grown. In fact, Bio-Organic farming products do not require any pesticides or herbicides, but they use soil fertility without any chemical addiction. <br><br> Organic is booming. Increased understanding of what organic means has changed the face of organic shoppers. Today, there is not one typical organic consumer, so we can ask ourselves how this will shape the product offerings of tomorrow? The perception that organic products are healthier motivates consumers to purchase more organic products. Especially among the younger consumers, whose desires for healthy food options and concerns about the potential effects of pesticides, hormones, GMO’s and antibiotics, along with the desire to avoid highly-processed food and artificial ingredients are top reasons to buy organic. <br><br> <b><h2>Organic products</h2></b> <br> Organic products are considered to be the most natural and healthy. The rich nutritional value of organic fruits and vegetables is the main reason for their demand both in the domestic and international markets. <br><br> Nowadays more and more products are grown in an organic way: vegetables, fruit, legumes, and cereals. Bio food market is growing and expanding fast. <br><br> <b><h2>Bio organic stores</h2></b> <br> Bio organic shops are on every corner, but not only that - Bio online shops are now new reality not only for the vegetarians or vegans, but also for those who are more into bio in food; they are aware of the eco-systems and benefits of organically produced food. <br> Bio food shops are offering variety of products, starting bio classics: milk, veggies, cheese. But the choice is now much bigger: sweets, deserts, cleaning products, even clothes!<br><br>Check bio food online shop in our Services section. Choose to visit our farms, buy or deliver.",
    "image": "/blog-4.jpg",
    "keywords": "Bio organic shop, Bio food shop, Bio organic store, Bio food online shop, Bio food market"
  },
  {
    "slug": "locations-of-our-farms",
    "title": "Locations of our farms",
    "author": "Max Ka",
    "authorRole": "Graphic Designer, educator & CEO BioFood",
    "date": "June 05, 2023",
    "description": "Our farms are always on outside of a city locations. They are covered in Sun, surrounded by mountains and beautiful meadows.",
    "body": "What is an organic product? An organic product is a product that is grown without the use of chemicals, fertilizers, pesticides, growth hormones, GMOs, etc. Moreover, a few years before the start of the cultivation of organic products, the land on which they will be cultivated must be completely cleared of the chemicals used earlier in order to prevent contact with new plants. If the farmer meets all these conditions, then he can receive an official certificate of organic production. Many seniors will tell you that all food used to be organic because so many chemicals were not used. In fact, chemical fertilizers and pesticides have been used for years not only by large producers, but also by farmers who grow for their own needs. According to experts, all products were organic until the introduction of nitrogen fertilizers in the early 20th century. Organic products are considered to be the most natural and healthy. The rich nutritional value of organic fruits and vegetables is the main reason for their demand both in the domestic and international markets. What are bio products? According to the European regulation, a bio-product is the same organic product and they do not differ from each other. The truth is, the difference is only in our personal perception. Some polls have shown that more people trust the “bio” marker than “organic”. Also, the use of these terms varies around the world. In Europe and surrounding countries, the term bio is more popular, while in English-speaking countries (USA, UK, Australia) you will more often come across the term “organic”. In conclusion, we want to say that “organic” and “bio” products are no different and you can trust certified producers – their product will definitely become a useful and important part of your healthy diet, as well as take care of the environment.",
    "image": "/blog-3.jpg",
    "keywords": "Bio foods, Bio organic products, Bio food products, Bio food company, Bio organic shop, Bio about food, Bio for food, Bio products food, Bio food shop, Bio in food, Bio organic market, Bio organic store, Bio veggies, Bio food online shop, Bio food market"
  }];